### ISSUE TITLE
Instrument names

### ISSUE THREAD

**Issue by gminef** [c-yanguas/Menu-Callisto#1]
Thank you for this very useful tool! 

I noticed that the the script uses the instrument name "INDIA-GAURI" for the GAURI instrument. 

Since this observatory uses in the data filenames only the name "GAURI", attempts to download its data with the name "INDIA-GAURI" results in an empty folder. 

Please update the instrument names with the observatory codes actually used in the filenames: e.g. replace "INDIA-GAURI" with "GAURI" so the download attempt is successful.

**Comment by c-yanguas** [comment]
Hello gminef, im glad this tool help to your pourpose.
Could you please tell me which dates are you trying to download?, maybe old data is with GAURI, however, I can see that for example for 31-01-2022, the name of that station is INDIA-GAURI.

![image](https://user-images.githubusercontent.com/95175204/167294765-bede6fac-2bca-4d29-828c-ef07c274aeac.png)

And I have been able to download it also:

![image](https://user-images.githubusercontent.com/95175204/167294776-eb20d982-bec2-4749-90dc-9628ada1d323.png)


**Note that in some intervals, data is not available for specific some stations, in that case, if you select dates for that station in that specific period, the programm will try to download it, and since is not data available the result will be an empty folder**

**Comment by gminef** [comment]
Thanks for the answer!

I see, in the new files the code "INDIA-GAURI" is used... However for the years 2013-2014, it is only "GAURI". I manually changed the name and I could download the files without any problem.

**Comment by c-yanguas** [comment]
Good Job gminef and thanks for the feedback about the tool, I really apreciate it.
Just in case anyone else have some related problem,  as gminef already explained, in main.py you can customize your own station names, I have only include the most recent ones:
![image](https://user-images.githubusercontent.com/95175204/167295147-645e1150-53e3-4d8b-b0fd-7e07048dbc64.png)
